### ISSUE TITLE
[Orangelight/production] NoMethodError: undefined method `empty?' for nil:NilClass

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/orangelight#1337]
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/39194130)

**Comment by tpendragon** [comment]
Removing myself from this ticket. pulibrary/requests#375 should fix this, but the tests failed for apparently unrelated reasons, so I'm backing off until we can clear that up.

**Comment by escowles** [comment]
This is not fixed — just checked HoneyBadger and the latest instance is 15 hours ago: https://app.honeybadger.io/projects/54399/faults/37070237

**Comment by tampakis** [comment]
If this happens again we will open a new ticket
